### ISSUE TITLE
Organisation type filter for envelope report - defaults to 'all types'

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#345]
And should also be a 'multi-select'

I think this is the quickest way to solve this issue for now.

**Comment by matmaxgeds** [comment]
there also appears to be a bug after making it multi-select i.e. even when all are selected, no individual organisations are available in the organisations dropdown

**Comment by raashidahmad** [comment]
Fixed now. Please see the organizations management page before testing this feature. Most of the organizations are of type Government.

**Comment by matmaxgeds** [comment]
@raashidahmad - thanks, this fix works, but I had hoped that it would influence the report e.g. when I change just this organisation type filter, then nothing changes in the report, it should change the availability of the organisation in the filter/dropdown to the right where you can select specific organisation i.e. if you select org_type = NGO, then a) in the specific organisation dropdown, orgs with the org_type=NGO should be available, and only NGOs should be shown in the report/table

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the test. Please check it with Government type, and you will see right side will load the organizations. Actually, we have not entered organizations for other types, or from import the types are mostly Government.

**Comment by matmaxgeds** [comment]
@raashidahmad agreed, that part works perfectly, the issue is that if I select 'multilateral' of an org_type where we do not have any orgs yet, then I still get the government orgs in the chart......using the org_type filter should filter the results returned, even if the user does not do anything with the second org filter, (the org_name filter)

**Comment by raashidahmad** [comment]
@matmaxgeds understood. In reports we normally press the update report button to update the whole report loaded from server, and this includes the generation of Excel as well. I think if i allow the change without update report button, it will create inconsistencies.

**Comment by matmaxgeds** [comment]
@raashidahmad this is a misunderstanding, updating the org type filter should affect the orgs available in the org selection dropdown (as normal, the default should be that all are selected).

As you say, the chart should only actually update when the user presses the update report button.

**Comment by raashidahmad** [comment]
@matmaxgeds By default, all is selected, by selecting org types, relevant orgs loaded. Closing it just to make you notice.

**Comment by matmaxgeds** [comment]
Thanks - when I tested this morning, it was not working as I had expected so think I was not clear enough - at the moment, if I ignore the first organisation dropdown (organisation type), then in the second one (specific organisation), it says 'no data'? I would like it to show 'all organisations' in situations where the user ignores the organisation type dropdown, i.e. the default for the 'organisation type' dropdown is that all options are selected, unless the users uses the dropdown and selects a sub-set of organisation types - is that possible?

**Comment by raashidahmad** [comment]
Ah okay, got it now. Will do the fix

**Comment by raashidahmad** [comment]
Fixed. Now when no org type is selected, By default, all organizations are listed in the dropdown.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks

1. It should not show organisations for which there is no envelope data
2. This way of doing organisation type (with the second filter) needs to be on all the reports, not just the envelope report

**Comment by raashidahmad** [comment]
Changes implemented. Please review. Closing it for your notice.

**Comment by matmaxgeds** [comment]
@raashidahmad - this works, except when there are no orgs matching the org_type selected, it currently shows all data in this situation, but instead, there should be no data in the chart/table if there are no orgs matching the org type the user has selected

**Comment by raashidahmad** [comment]
@matmaxgeds this is implemented.
